name: titrate-dev
channels:
  - conda-forge
  - default
dependencies:
  - python=3.11
  - gammapy=1.2
  - numpy
  - scipy
  - matplotlib
  - pytest
  - pre-commit
  - ipython
  - black
  - jupyter 
  - pip
